### PR TITLE
Add linting and warning config and fix some lints

### LINKED ISSUE #9: Set up cargo and clippy config files for linting and warnings

### PR DESCRIPTION
**Pull request by elshize**
Fixes #9

### CODE REVIEW

File: rust/src/main.rs [hunk 1]
```diff
@@ -80,14 +86,15 @@ fn gen(args: Args) -> Result<()> {
 
     // Read protobuf header
     let header = input.read_message::<Header>()?;
-    let num_documents = header.get_num_docs();
+    let num_documents =
+        u32::try_from(header.get_num_docs()).expect("Number of documents must be non-negative.");
```
Comment (elshize) [inline rust/src/main.rs]: @JMMackenzie I changed a few lines and I thought you might be interesting why. This is the first of them, I use `TryFrom` trait's `try_from` function here, which `u32` implements on `i32`. Essentially, it will return `Err` if can't construct, so when it's negative. Just a little bit of code to explicitly fail instead of a generic panic. In most situations you'd propagate this error with `?` but it doesn't really matter to us here (we'll fail anyway), and this gives me a way to put a custom error message. Ideally, you'd use one of the error handling libraries, and call something like `.context("...")?` instead of expect but hey, I'm lazy :D

File: rust/src/main.rs [hunk 2]
```diff
@@ -110,14 +117,14 @@ fn gen(args: Args) -> Result<()> {
         encode_sequence(
             &mut frequencies,
             length,
-            postings.iter().map(|p| p.get_tf()),
+            postings.iter().map(Posting::get_tf),
```
Comment (elshize) [inline rust/src/main.rs]: This is an interesting little thing: you can do this thing because really `get_tf` acts as a free function with an argument that is a reference to `Posting`. This makes it easy to use methods like that.

File: rust/src/main.rs [hunk 3]
```diff
@@ -128,9 +135,9 @@ fn gen(args: Args) -> Result<()> {
     let mut sizes = BufWriter::new(File::create(format!("{}.sizes", args.output))?);
     let mut trecids = BufWriter::new(File::create(format!("{}.documents", args.output))?);
 
-    let bar = ProgressBar::new(num_documents as u64);
-    bar.set_style(pb_style());
-    bar.set_draw_delta(num_documents as u64 / 100);
+    let progress = ProgressBar::new(u64::from(num_documents));
```
Comment (elshize) [inline rust/src/main.rs]: Here, I'm using `from` instead of `as` for robustness really, if somehow `num_documents` changes type for whatever reason, `as` might behave shady, whereas `from` won't accept anything that's not kosher.
